//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_ForEmployees.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public string EmpName { get; set; }
        public int EmpId { get; set; }
        public string Department { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Job { get; set; }
    }
}
